/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SetMomentLocalePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/locale.ts
var locales = {
  "af": "Afrikaans",
  "sq": "Albanian",
  "ar": "Arabic",
  "ar-dz": "Arabic (Algeria)",
  "ar-kw": "Arabic (Kuwait)",
  "ar-ly": "Arabic (Libya)",
  "ar-ma": "Arabic (Morocco)",
  "ar-sa": "Arabic (Saudi Arabia)",
  "ar-tn": "Arabic (Tunisia)",
  "hy-am": "Armenian (Armenia)",
  "az": "Azerbaijani",
  "bm": "Bambara",
  "bn-bd": "Bangla (Bangladesh)",
  "eu": "Basque",
  "be": "Belarusian",
  "bn": "Bengali",
  "bs": "Bosnian",
  "br": "Breton",
  "bg": "Bulgarian",
  "my": "Burmese",
  "ca": "Catalan",
  "tzm": "Central Atlas Tamazight",
  "tzm-latn": "Central Atlas Tamazight (Latin)",
  "km": "Central Khmer",
  "zh-hk": "Chinese (Hong Kong)",
  "zh-mo": "Chinese (Macao)",
  "zh-cn": "Chinese (PRC)",
  "zh-tw": "Chinese (Taiwan)",
  "cv": "Chuvash",
  "hr": "Croatian",
  "cs": "Czech",
  "da": "Danish",
  "nl-be": "Dutch (Belgium)",
  "nl": "Dutch (Standard)",
  "en": "English",
  "en-au": "English (Australia)",
  "en-ca": "English (Canada)",
  "en-in": "English (India)",
  "en-ie": "English (Ireland)",
  "en-il": "English (Israel)",
  "en-nz": "English (New Zealand)",
  "en-sg": "English (Singapore)",
  "en-gb": "English (United Kingdom)",
  "eo": "Esperanto",
  "et": "Estonian",
  "fo": "Faeroese",
  "fa": "Farsi",
  "fil": "Filipino",
  "fi": "Finnish",
  "fr-ca": "French (Canada)",
  "fr": "French (Standard)",
  "fr-ch": "French (Switzerland)",
  "gd": "Gaelic (Scotland)",
  "gl": "Galician",
  "ka": "Georgian",
  "de-at": "German (Austria)",
  "de": "German (Standard)",
  "de-ch": "German (Switzerland)",
  "gom-deva": "Goan Konkani (Devanagari)",
  "gom-latn": "Goan Konkani (Latin)",
  "el": "Greek",
  "gu": "Gujarati",
  "he": "Hebrew",
  "hi": "Hindi",
  "hu": "Hungarian",
  "is": "Icelandic",
  "id": "Indonesian",
  "ga": "Irish",
  "it": "Italian (Standard)",
  "it-ch": "Italian (Switzerland)",
  "ja": "Japanese",
  "jv": "Javanese",
  "kn": "Kannada",
  "kk": "Kazakh",
  "tlh": "Klingon",
  "ko": "Korean",
  "ku": "Kurdish",
  "ky": "Kyrgyz",
  "lo": "Lao",
  "lv": "Latvian",
  "lt": "Lithuanian",
  "lb": "Luxembourgish",
  "mk": "Macedonian (FYROM)",
  "ms-my": "Malay (Malaysia)",
  "ml": "Malayalam",
  "ms": "Malaysian",
  "dv": "Maldivian",
  "mt": "Maltese",
  "mi": "Maori",
  "mr": "Marathi",
  "mn": "Mongolian",
  "me": "Montenegro",
  "ne": "Nepali",
  "se": "Northern Sami",
  "nb": "Norwegian (Bokm\xE5l)",
  "nn": "Norwegian (Nynorsk)",
  "oc-lnc": "Occitan",
  "pl": "Polish",
  "pt-br": "Portuguese (Brazil)",
  "pt": "Portuguese (Portugal)",
  "pa-in": "Punjabi (India)",
  "ro": "Romanian",
  "ru": "Russian",
  "sr": "Serbian",
  "sr-cyrl": "Serbian(cyrl)",
  "sd": "Sindhi",
  "si": "Sinhalese",
  "sk": "Slovak",
  "sl": "Slovenian",
  "es-do": "Spanish (Dominican Republic)",
  "es-mx": "Spanish (Mexico)",
  "es": "Spanish (Spain)",
  "es-us": "Spanish (United States)",
  "sw": "Swahili",
  "ss": "Swati",
  "sv": "Swedish",
  "tl-ph": "Tagalog (Philippines)",
  "tg": "Tajik",
  "tzl": "Talossan",
  "ta": "Tamil",
  "te": "Telugu",
  "tet": "Tetum",
  "th": "Thai",
  "bo": "Tibetan",
  "tr": "Turkish",
  "tk": "Turkmen",
  "uk": "Ukrainian",
  "ur": "Urdu",
  "ug-cn": "Uyghur (China)",
  "uz": "Uzbek",
  "uz-latn": "Uzbek (Latin)",
  "vi": "Vietnamese",
  "cy": "Welsh",
  "fy": "Western Frisian",
  "yo": "Yoruba"
};

// src/main.ts
var DEFAULT_SETTINGS = {
  locale: "en"
};
var SetMomentLocalePlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SettingTab(this.app, this));
    for (const locale of window.moment.locales()) {
      if (locale !== this.settings.locale) {
        window.moment.updateLocale(locale, null);
      }
    }
    window.moment.updateLocale(this.settings.locale, {});
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", {
      text: `WARNING: DO NOT DELETE or DISABLE this plugin.`,
      attr: { style: "color: red" }
    });
    const text = containerEl.createEl("p");
    text.createEl("span", {
      text: `Obsidian basically does NOT support to change internal "moment.js" locale.`
    });
    text.createEl("br");
    text.createEl("span", {
      text: `As a result, I couldn't fix the bug where the locale does not change when the plugin is disabled.`
    });
    new import_obsidian.Setting(containerEl).setName("Locale").setDesc("* Restart needed").addDropdown((dropdown) => {
      for (const code in locales) {
        dropdown.addOption(code, locales[code]);
      }
      dropdown.setValue(this.plugin.settings.locale).onChange(async (value) => {
        this.plugin.settings.locale = value;
        await this.plugin.saveSettings();
      });
    });
  }
};

/* nosourcemap */